brew "coreutils"
brew "gnu-sed"
brew "gnu-tar"
brew "grep"
brew "watch"
brew "findutils"
brew "curl"
brew "the_silver_searcher"
brew "stow"
brew "git"
brew "bash"
brew "zsh"
brew "tmux"
brew "fzf"
brew "jq"
brew "neovim"
brew "emacs"
brew "htop"
brew "ncdu"
brew "tig"
brew "go"
brew "gimme"
brew "python"
brew "openblas" # https://github.com/numpy/numpy/issues/17784#issuecomment-729950525
brew "pyenv"
brew "pyenv-virtualenv"
brew "zlib" # pyenv dependency
brew "pipenv"
brew "node"
brew "npm"
brew "rustup"
brew "java"
brew "loc"
brew "cmatrix"
brew "pandoc"
brew "tldr"
brew "unrar"
brew "sshuttle"
brew "qcachegrind"
brew "lz4"
brew "tree"
brew "geckodriver"
brew "wget"
brew "youtube-dl"
brew "ffmpeg"
brew "exiftool"
brew "gzip"
brew "unzip"

tap "homebrew/cask"
cask "google-chrome"
cask "brave-browser"
cask "firefox"
cask "tor-browser"
cask "iterm2"
cask "spotify"
cask "visual-studio-code"
cask "calibre"
cask "bitwarden"
cask "telegram"
cask "whatsapp"
cask "evernote"
cask "libreoffice"
cask "typora"
cask "vlc"
cask "mactex"
cask "dash"
cask "karabiner-elements"
cask "transmission"
cask "adobe-acrobat-reader"
cask "adobe-creative-cloud"
cask "musicbrainz-picard"
cask "drawio"
cask "istat-menus"
cask "postman"
cask "monitorcontrol"
cask "netnewswire"
cask "virtualbox"

tap "homebrew/cask-versions"

tap "homebrew/cask-fonts"
cask "font-fira-code"
cask "font-cascadia"

tap "homebrew/cask-drivers"
cask "logitech-options"

tap "bazelbuild/tap"
brew "bazel"

tap "heroku/brew"
brew "heroku"
brew "heroku-node"  # heroku dependency, not properly resolved by brew bundle
