brew "coreutils"
brew "gnu-sed"
brew "grep"
brew "the_silver_searcher"
brew "stow"
brew "git"
brew "bash"
brew "zsh"
brew "tmux"
brew "fzf"
brew "neovim"
brew "htop"
brew "ncdu"
brew "tig"
brew "go"
brew "gimme"
brew "python"
brew "pyenv"
brew "pipenv"
brew "node"
brew "npm"
brew "rustup"
brew "loc"
brew "cmatrix"
brew "pandoc"
brew "tldr"
brew "qcachegrind"
brew "tree"
brew "wget"

tap "homebrew/cask"
cask "google-chrome"
cask "brave-browser"
cask "firefox"
cask "iterm2"
cask "java"
cask "spotify"
cask "visual-studio-code"
cask "calibre"
cask "1password"
cask "telegram"
cask "whatsapp"
cask "typora"
cask "vlc"
cask "karabiner-elements"
cask "drawio"

tap "homebrew/cask-fonts"
cask "font-fira-code"
cask "font-cascadia"

tap "homebrew/cask-drivers"
cask "logitech-options"

# datadog

tap "datadog/tap" "git@github.com:DataDog/homebrew-tap.git"
cask "datadog/tap/python@2"
cask "ddtool"

brew "tfenv"
brew "awscli@1"
brew "vault"
brew "google-cloud-sdk"
brew "kubectx"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "rbenv"

cask "virtualbox"
cask "vagrant"
