version: "1"

global:
  scheduler: crond
  log: "resticprofile.log"

base:
  backup:
    verbose: true
    check-after: true
    source:
      # zsh history
      - "/Users/francisco/.zsh_history"

      # all git repositories cloned locally
      - "/Users/francisco/dev"

      # mostly for the screenshots folder
      - "/Users/francisco/Pictures"

      # Google Drive
      - "/Users/francisco/My Drive"

      # iCloud Drive
      - "/Users/francisco/Library/Mobile Documents/com~apple~CloudDocs"

      # obsidian vaults
      - "/Users/francisco/Library/Mobile Documents/iCloud~md~obsidian"

    exclude:
      # iPhotos library
      - "/**/*.photoslibrary"

      # Photo Booth Library
      - "/**/Photo Booth Library/"

      # node_modules (they have way too many files, they make the backup slow)
      - "/**/node_modules/"

      # Yarn cache
      - "/**/.yarn/"

      # Vercel deployment cache
      - "/**/.vercel/"

      # Python virtual environments (regenerable via pip)
      - "/**/.venv/"
      - "/**/venv/"
      - "/**/__pycache__/"
      - "/**/*.pyc"

      # Rust build output (regenerable via cargo build)
      - "/**/target/debug/"
      - "/**/target/release/"

      # Rust cross-compilation targets (target triples like wasm32-unknown-unknown)
      - "/**/target/*-*-*/"

      # iOS/macOS CocoaPods (regenerable via pod install)
      - "/Users/francisco/dev/**/Pods/"

      # Xcode derived data (standard location, regenerable)
      - "/Users/francisco/Library/Developer/Xcode/DerivedData/"

      # Go modules cache
      - "/**/go/pkg/mod/"

      # macOS system files (always regenerated)
      - "/**/.Spotlight-V100/"
      - "/**/.Trashes/"
      - "/**/.fseventsd/"
      - "/**/.DS_Store"

      # Caches (explicitly designed to be disposable)
      - "/**/Library/Caches/"
      - "/**/.cache/"

      # Vim swap files
      - "/**/*.swp"
      - "/**/*.swo"

    schedule: "*-*-* 12,20:00:00"
    schedule-permission: user
    # schedule-ignore-on-battery: true

  retention:
    before-backup: false
    after-backup: true
    prune: true
    keep-within: 60d
    keep-weekly: 52
    keep-monthly: 36
    keep-yearly: unlimited

puigfp: # Macbook Pro 14 M3 Pro
  inherit: base
  backup:
    host: puigfp
  retention:
    host: puigfp # only consider snapshots from this host for pruning

puigfp-2025-12-23: # Macbook Pro 14 M1 Max (bought back when I left Datadog)
  inherit: base
  backup:
    host: puigfp-2025-12-23
  retention:
    host: puigfp-2025-12-23 # only consider snapshots from this host for pruning
